name: CI

on: [push]

jobs:
  build:

    runs-on: node:latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run 
      run: |
        npm install
        npm install mocha
        npm test
