name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-14.04, ubuntu-18.04]
        node: [6, 8, 10]
    
    steps:
    - uses: actions/checkout@v1
    - name: Run 
      run: |
        npm install
        npm install mocha
        npm test
